version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "test"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ""

  apache:
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
      - ./apache-config/httpd.conf:/opt/lampp/apache2/conf/httpd.conf

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - SE_EVENT_BUS_PUBLISH_PORT=5555
      - SE_EVENT_BUS_SUBSCRIBE_PORT=5556

  selenium-node-firefox:
    image: selenium/node-firefox:latest
    container_name: selenium-node-firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=5555
      - SE_EVENT_BUS_SUBSCRIBE_PORT=5556
    entrypoint: ["/bin/bash", "-c", "sleep 30 && /opt/bin/entry_point.sh"]

  selenium-node-chrome:
    image: selenium/node-chrome:latest
    container_name: selenium-node-chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=5555
      - SE_EVENT_BUS_SUBSCRIBE_PORT=5556
    entrypoint: ["/bin/bash", "-c", "sleep 30 && /opt/bin/entry_point.sh"]

  spring-boot:
    image: wms:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - apache
      - selenium-hub
      - selenium-node-chrome
      - selenium-node-firefox
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3