version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true" # Set MYSQL_ALLOW_EMPTY_PASSWORD to true
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "test"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: ""

  apache:
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
      - ./apache-config/httpd.conf:/opt/lampp/apache2/conf/httpd.conf

  spring-boot:
    image: wms:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - apache
