name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Well done on creating your first issue!!"
        pr-message: "Well done on creating your first pull request!!"
